apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-service
  name: inventory-service
  namespace: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - image: 936068047509.dkr.ecr.us-east-1.amazonaws.com/inventory-service:latest
        name: inventory-service
        ports:
        - containerPort: 5000
        resources: # Verify the amount of requests
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: OTLP
          value: "otel-collector.otel-collector.svc.cluster.local"
        - name: DATABASE
          value: "database-service.database-service.svc.cluster.local"
        - name: LOGS
          value: "" # Analytics Service
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: inventory-service
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: inventory-service